# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - cd vue-client
            - yarn -install
            - yarn global add gulp
            - yarn test:unit
            - set +e
            - yarn lintExport
            - set -e
            - gulp sonar

